// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: docgen.proto

package docgenpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocService_GetPlaceholders_FullMethodName = "/docgen.DocService/GetPlaceholders"
	DocService_GeneratePDF_FullMethodName     = "/docgen.DocService/GeneratePDF"
	DocService_GenerateDocx_FullMethodName    = "/docgen.DocService/GenerateDocx"
)

// DocServiceClient is the client API for DocService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocServiceClient interface {
	// Mengembalikan daftar placeholder ditemukan di template DOCX
	GetPlaceholders(ctx context.Context, in *TemplateRequest, opts ...grpc.CallOption) (*PlaceholderResponse, error)
	// Generate PDF dari template DOCX + data
	GeneratePDF(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	// (opsional) hanya hasil DOCX
	GenerateDocx(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type docServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocServiceClient(cc grpc.ClientConnInterface) DocServiceClient {
	return &docServiceClient{cc}
}

func (c *docServiceClient) GetPlaceholders(ctx context.Context, in *TemplateRequest, opts ...grpc.CallOption) (*PlaceholderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceholderResponse)
	err := c.cc.Invoke(ctx, DocService_GetPlaceholders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) GeneratePDF(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, DocService_GeneratePDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) GenerateDocx(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, DocService_GenerateDocx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocServiceServer is the server API for DocService service.
// All implementations must embed UnimplementedDocServiceServer
// for forward compatibility.
type DocServiceServer interface {
	// Mengembalikan daftar placeholder ditemukan di template DOCX
	GetPlaceholders(context.Context, *TemplateRequest) (*PlaceholderResponse, error)
	// Generate PDF dari template DOCX + data
	GeneratePDF(context.Context, *GenerateRequest) (*GenerateResponse, error)
	// (opsional) hanya hasil DOCX
	GenerateDocx(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedDocServiceServer()
}

// UnimplementedDocServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocServiceServer struct{}

func (UnimplementedDocServiceServer) GetPlaceholders(context.Context, *TemplateRequest) (*PlaceholderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaceholders not implemented")
}
func (UnimplementedDocServiceServer) GeneratePDF(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePDF not implemented")
}
func (UnimplementedDocServiceServer) GenerateDocx(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDocx not implemented")
}
func (UnimplementedDocServiceServer) mustEmbedUnimplementedDocServiceServer() {}
func (UnimplementedDocServiceServer) testEmbeddedByValue()                    {}

// UnsafeDocServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocServiceServer will
// result in compilation errors.
type UnsafeDocServiceServer interface {
	mustEmbedUnimplementedDocServiceServer()
}

func RegisterDocServiceServer(s grpc.ServiceRegistrar, srv DocServiceServer) {
	// If the following call pancis, it indicates UnimplementedDocServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocService_ServiceDesc, srv)
}

func _DocService_GetPlaceholders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).GetPlaceholders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_GetPlaceholders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).GetPlaceholders(ctx, req.(*TemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_GeneratePDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).GeneratePDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_GeneratePDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).GeneratePDF(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_GenerateDocx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).GenerateDocx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_GenerateDocx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).GenerateDocx(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocService_ServiceDesc is the grpc.ServiceDesc for DocService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docgen.DocService",
	HandlerType: (*DocServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPlaceholders",
			Handler:    _DocService_GetPlaceholders_Handler,
		},
		{
			MethodName: "GeneratePDF",
			Handler:    _DocService_GeneratePDF_Handler,
		},
		{
			MethodName: "GenerateDocx",
			Handler:    _DocService_GenerateDocx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docgen.proto",
}
